name: Run Tests
on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Run Tests
        run: tox
